/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Ajout_gest_Utilis;
  GtkWidget *Modifie_gest_Utilis;
  GtkWidget *Supprimer_gest_Utilis;
  GtkWidget *Gestion_Utilisateur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 /* Ajout_gest_Utilis = create_Ajout_gest_Utilis ();
  gtk_widget_show (Ajout_gest_Utilis);
  Modifie_gest_Utilis = create_Modifie_gest_Utilis ();
  gtk_widget_show (Modifie_gest_Utilis);
  Supprimer_gest_Utilis = create_Supprimer_gest_Utilis ();
  gtk_widget_show (Supprimer_gest_Utilis);*/
  Gestion_Utilisateur = create_Gestion_Utilisateur ();
  gtk_widget_show (Gestion_Utilisateur);

  gtk_main ();
  return 0;
}

